name: Teste backend

defaults:
  run:
    working-directory: "backend/"

on:
  workflow_dispatch:
  push:
    branches:
    - backend

env:
  USER: ${{ github.actor }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  REGISTRY: ghcr.io
  IMAGE_NAME: bootcamp-frontend
  IMAGE_VERSION: 1.0.0

jobs:
  Teste:
    name: Teste backend
    runs-on: self-hosted

    steps:
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get -y install maven
            
    - name: Run tests
      run: mvn clean test

    - name: Build do java
      run: mvn clean package

    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ env.GH_TOKEN }}
        
    - name: Set up Docker Buildx
      run: docker/setup-buildx-action@v2        
      
    - name: Build Backend Dockerfile
      run: |
        cd ..
        docker build . --tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
    - name: Tag Backend Docker image
      run: docker tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }} ${{ env.REGISTRY }}/${{ env.USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}

    - name: Push Backend Docker image
      run:  docker push ${{ env.REGISTRY }}/${{ env.USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}

