
name: Teste frontend

defaults:
  run:
    working-directory: "frontend/app"

on:
  workflow_dispatch:
  push:
    branches:
    - frontend

jobs:
  Teste:
    name: Teste frontend
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - uses: ng-easy/npm-install@v2
      - run: npm run build
