name: Teste frontend

defaults:
  run:
    working-directory: "frontend/"

on:
  workflow_dispatch:
  push:
    branches:
    - frontend

jobs:
  Teste:
    name: Teste front
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Install node
      uses: actions/setup-node@v1    
      with:
        node-version: '16.x'
        
    - name: Install dependencies
      run: npm install
      
    - name: Install Angular CLI
      run: npm install -g @angular/cli
      
    - name: Ir para diretorio app
      run: cd app       
            
    - name: Run Tests
      run: ng test
