name: Teste frontend

defaults:
  run:
    working-directory: "frontend/app"

on:
  workflow_dispatch:
  push:
    branches:
    - frontend

jobs:
  Teste:
    name: Teste frontend
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Install node
      uses: actions/setup-node@v1    
      with:
        node-version: '16.x'
        
    - name: Install dependencies
      run: sudo apt-get update apt-get update && apt-get -y install npm
      
    - name: Install Angular CLI
      run: sudo apt-get update npm install -g @angular/cli
            
    - name: Run Tests
      run: ng test
      
      
