name: Teste frontend

defaults:
  run:
    working-directory: "frontend/app"

on:
  workflow_dispatch:
  push:
    branches:
    - frontend

jobs:
  Teste:
    name: Teste frontend
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Install node
      uses: actions/setup-node@v1    
      with:
        node-version: '16.x'
             
    - name: Install Angular CLI
      run: npm install -g @angular/cli > /dev/null
            
    - name: Run tests
      run: npm run test

    - name: Build
      run: npm run build
